services:
  db:
    image: mysql:8.4
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db